### ISSUE TITLE
TryParse on a value generated by FlakeId occassionally results in a FlakeId with a value of 0

### ISSUE THREAD

**Issue by fig-nwebb** [aevitas/flakeid#6]
The title pretty much says it.  I'm not to a point yet that code has reach production, so _maybe_ this is a dev/debug time concern only, but I've repeatedly ran into this issue where:

1. Use FlakeId to generate a value, then persist it somewhere.
2. Receive the same value as user input.  Use FlakeId.Id.TryParse to confirm the user provided value it at least sane.
3. Parsed value occassionally comes back as a FlakeId with a value of 0.

When trying to troubleshoot the issue, it appears that the Process ID component of the initial value (after bit manipulations within IsSnowflake()) is coming back as 0.

**Comment by aevitas** [comment]
Alright so I've been digging into this a bit further, and I've been able to reproduce the issue you describe. The following IDs (wrongly) throw a `FormatException` when passed to `IsSnowflake()`, which will cause both `Parse` and `TryParse` to fail:

```
1108047352848760832
1108047352848760832
1108047352852955136
1108047352865538048
1108047352865538048
1108047352869732352
```

The reason this fails is that `IsSnowflake` reversed the bitshifting that's being done when a Snowflake ID is created, to determine if all the components of the provided ID are logical. A more apt name would be `IsProbablySnowflake()`, because the method can never guarantee the ID passed is actually a snowflake, it can only assert that it matches all the characteristics of a snowflake, and if it looks like a snowflake and smells like a snowflake...

There's one thing the `IsSnowflake()` method does wrong though, and it's in this line:

```csharp
timestamp > 0 && thread > 0 && process > 0 && increment >= 0;
```

Because `increment` _can_ and _will_ be 0 for the first generated ID in an instance, and if you're rapidly generating IDs, and since the increment component is only 12 bits, it will eventually overflow (safely) back to 0, and you'll get another ID with increment zero.

Therefore, the check that `IsSnowflake()` performs is wrong, it should be `timestamp > 0 && thread > 0 && process > 0 && increment >= 0` instead.

I'll make the changes and release a new minor version that will address the issue. All your previously generated IDs are still fine, and can be used even in a production scenario. Let me know if the new version fixes the problem.

Thanks again for reporting!
